### ISSUE TITLE
[ ENHANCEMENT ] PS Vita/Weaker hardware ports

### ISSUE THREAD

**Issue by Girotin** [libretro/bsnes-libretro#11]
The snes9x cores aged very bad, and considering that bsnes has a lot better emulation than pretty much any version of snes9x, it would be awesome to see it running it in weaker hardware someday;

I know that bsnes actually isn't something optmized enough for something like running on 0.3ghz CPUs, but if someday it manages to get really far in optimization, please consider bringing it to lower end hardware, it's really painful seeing how nice it is running on PCs and Android, and needing to deal with slowdowns and graphical glitches with 90s hardware emulation.

**Comment by carmiker** [comment]
This is never happening, the emulator is just not written such that it could ever be optimized to such levels. Try https://github.com/libretro/supafaust if you don't like snes9x :).
