### ISSUE TITLE
runahead context awareness

### ISSUE THREAD

**Issue by barbudreadmon** [libretro/bsnes-libretro#22]
The `RETRO_ENVIRONMENT_GET_SAVESTATE_CONTEXT` api call was implemented a few months ago to allow the core to query about the context (1 or 2 instances runahead, netplay, normal) behind a savestate. My understanding is that this core currently uses a core option to get around the lack of such a feature, so maybe it should be reworked now that this is available ?

**Comment by carmiker** [comment]
Unfortunately, this is not going to work. The core option activates the internal runahead which was designed to handle all sorts of special cases, that is why it works. Using the "Fast" vs "Strict" states directly without using the internal runahead will break things horribly. Even SMW breaks :(.
