### ISSUE TITLE
Concerning DSP firmware

### ISSUE THREAD

**Issue by 71knight** [libretro/bsnes-libretro#28]
Bsnes does not seem to be applying the DSP lle firmware to the games.  Specifically pilotwings plane crashes short of the runway in the demo.  I have dsp1.data.rom and dsp1.program.rom in retroarch/system directory.  Retroarch core information says I have the correct firmware but the plane demo is still broken.  Maybe this is a regression?  Also would be nice if there was an indicator showing if lle or hle DSP emulation was being used.

**Comment by nanitaro** [comment]
It works fine on Mesen-S cores that use DSP firmware.
Therefore, it seems to be a problem specific to the Bsnes core.
The Prefer HLE option does not seem to work.

**Comment by nanitaro** [comment]
@carmiker
https://github.com/bsnes-emu/bsnes/issues/304
Please excuse this gentle reminder.
The problem is that the firmware is not loaded in Bsnes Libretro core.

**Comment by carmiker** [comment]
@nanitaro thanks for the reminder. I actually did forget about this, so I will just put it on my todo list for this week and hopefully actually have time to do it.

**Comment by carmiker** [comment]
@nanitaro it has been pushed, so if you are able to build it let me know how it works. Otherwise, feel free to wait until tomorrow's builds come out.

**Comment by nanitaro** [comment]
@carmiker
Thank you.
I confirmed it works with today's nightly build.
Games with expansion chips also seem to work.
Prefer HLE option also works fine. 
The Pilot Wings airplane demo lands correctly when HLE is disabled.

Also, Hayazashi Nidan Morita Shougi 2(equipped with ST-0018), which had stopped working, now works.
Shogi moves seem to be weaker than on the real machine, but this is a different problem.

I think this issue can be closed.
