### ISSUE TITLE
Adding option to disable the "gamma ramp" effect

### ISSUE THREAD

**Issue by JosepMC154** [libretro/bsnes-libretro#37]
What the title says: make Super Sleuth's gamma ramp optional in the RetroArch core instead of enabling it on by default, so that you can use either mode at will. Standalone bsnes has an option to enable the effect. 

Top is Snes9x and bottom is bsnes.

![Lufia Restored (v3 1) - Always Retry Mode-240613-225516](https://github.com/libretro/bsnes-libretro/assets/75935339/e60e816c-5156-47c5-bcd5-0981d6811b1b)
![Lufia Restored (v3 1) - Always Retry Mode-240613-225458](https://github.com/libretro/bsnes-libretro/assets/75935339/2104ae07-cd81-4d7b-839b-42cca367495b)

**Comment by carmiker** [comment]
@JosepMC154, I have this written but the hard part for me is naming the setting and filling in my own information gaps about it. I don't know any background info about how it came to be, or who Super Sleuth is/was. All I know is how to turn the effect on and off :). Would you be able to provide more details?

**Comment by carmiker** [comment]
Nevermind, I just copied the ranges and terminology from the standalone frontend. It's done.

**Comment by JosepMC154** [comment]
Thank you so much! It works, but the gamma value is still 150% by default whenever I boot a game anew, even after setting it to 100% and saving the settings. That is to say, the parameter is saved to 100% and shows so after running bsnes again, but the core still applies the default settings for all thee colours parameters (e.g. luminance/saturation will still default to 100% even if you change it), and the new settings will only apply the moment you change them.

I also saw that the bsnes-hd beta core already had the colour adjustement settings and it applies them just fine after saving them, so maybe you can just look at how that handles it and take it from there.

**Comment by carmiker** [comment]
I've reopened the issue, I'll wait for you to confirm the latest fix works. I was able to reproduce it, it was a very simple fix (move a line below another one :) ).

**Comment by JosepMC154** [comment]
Now it saves properly for me too. Thank you again mate! Happy gaming!

**Comment by joepogo** [comment]
Hey @carmiker , great work on all of this mate! I had a question, i know this is a different issue, but will this fix/help fix the distortion with using the NTSC filter options you added back into BSNES a few months ago? Which i might add, is a welcome addition and i am sure i speak for many when i say thank you so much! :)

When using the composite and RF filter options the pixels/resolution gets distorted and the color changes to way too dark, (example, the life bar on megaman X i use for testing these out) but S-video and RGB stay unaffected and fine. I am not sure but using the same options on SNES(X it does not do this, so i am hoping it is a fixable issue with BSNES. 

Anywho, i hope you are well and thanks again for your continued commits for BSNES on retroarch. :)

**Comment by carmiker** [comment]
@joepogo that is just inherent to blargg's NTSC filter. I think your best bet is to use a shader to accomplish the same goal. The SNES outputs RGB, so really, if you want to reproduce the best original experience (the SNES outputting RGB to a PVM), then not even using blargg's filter, and instead just a post-processing shader is going to be more effective at getting you there.
