### ISSUE TITLE
Add 12 and 16 Pixel Cropping Options

### ISSUE THREAD

**Issue by Awakened0** [libretro/bsnes-libretro#38]
Currently bsnes-libretro only supports cropping 8px off the top and bottom. snes9x and Mesen-S support cropping 16px off both, while snes9x also supports cropping 12px (from this pull https://github.com/libretro/snes9x/pull/258). 16px is particularly useful for Yoshi's Island (example screenshots in that snes9x pull.)

**Comment by carmiker** [comment]
Should be doable.

**Comment by carmiker** [comment]
I've just pushed the changes that should address the initial request. This could potentially be made more flexible in the future, (such as adding settings for horizontal masking and separate top/bottom masking), but I wanted to get the ball rolling and make sure to avoid any terrible regressions.

**Comment by Awakened0** [comment]
Checked it out, it made it into the last nightly of the day. All the cropping modes work as expected, don't see any issues.

If I wanted to nitpick with this initial implementation, the variable order isn't sequential. Starting with the default 8 lines, pressing right on the dpad changes it to 0, then 16, then 12 and back to 8. Little confusing, but not a big deal.

Thanks for adding this!
