### ISSUE TITLE
Is it possible to force the resolution back to 1x?

### ISSUE THREAD

**Issue by PlayNeth** [libretro/bsnes-libretro#8]
Title. the 2x resolution in the bsnes core messes up my shaders completely, and i dont see a setting in the core options to disable this. Sorry if this is the wrong place to ask but it's really driving me insane and i have no clue where else to do so.

**Comment by carmiker** [comment]
The way the emulator renders, it assumes max resolution at all times and doubles the width/height of pixels being rendered in the typical 256x240 mode, but only when using the accurate PPU. I fixed this in my own fork of the emulator, but doing it in this repository without major implications is not possible.
